descriptor-schema-version: "2.7"

info:
  name: IOxGPSd
  description: GPSd Service
  version: "0.92"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin

  type: docker

  resources:
    profile: custom
    cpu: "100"
    disk: "10"
    memory: "20" 
    network:
     -
       interface-name: eth0
       ports:
            tcp: [2947]
    devices:
      -
        type: serial
        label: GPS_DEV
        device-id: /dev/ttyS4
        usage: This is gps sensors

  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    #target: "/usr/sbin/gpsd -b -G -n /dev/ttyS4"
    target: 
      - "/usr/sbin/gpsd"
    args:
      - "-N -b -G -n /dev/ttyS4"
    #os-mode: true
    
