descriptor-schema-version: "2.5"

info:
  name: IOxGPSd
  description: GPSd Service
  version: "0.9"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker

  resources:
    profile: custom
    cpu: "100"
    disk: "10"
    memory: "20" 
    network:
     -
       interface-name: eth0
       ports:
            tcp: [2947]
    devices:
      -
        type: serial
        label: GPS_DEV
        device-id: /dev/ttyS4
        usage: This is gps sensors

  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/sbin/gpsd -b -G -n /dev/ttyS4"]
